server:
  port: 8084

spring:
  application:
    name: employee-info

  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.gmeqjfecykahhgyrukca
    password: Patel@123Yash

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  r2dbc:
    url: 

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://dev-98542581.okta.com/oauth2/default
    client:
      registration:
        my-client:
          provider: okta
          authorization-grant-type: client-credentials
          scope: api://default
          client-id: 0oanwp3vluL35pCWE5d7
          client-secret: kri3JQRqmWSRPtsWCOCth7QczK2YcFEkPJOhooFPAiLM0vqKVJ1_bbu5wJ7itscJ
      provider:
        okta:
          issuer-uri: https://dev-98542581.okta.com/oauth2/default

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      departmentAddressBreaker:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3   
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      departmentAddressRetry:
        max-attempts: 2
        wait-duration: 500ms  

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 5s   
        limit-for-period: 3     
        timeout-duration: 0s


